server:
  port: 7900 #指定eureka示例的端口号

eureka:
  instance:
    prefer-ip-address: true #是否显示主机的ip
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/     #指定eureka服务端的地址

spring:
  application:
    name: microservice-eureka-order #指定应用名称